name: Deploy to Ubuntu Server

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Generate .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DEBUG: ${{ secrets.DEBUG }}
          envkey_DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          envkey_DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          envkey_DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          envkey_DATABASE_USER: ${{ secrets.DATABASE_USER }}
          envkey_DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}

      - name: Build Docker images
        run: |
          docker build . -t todo-flask-app:${{ github.sha }}

  run:
    runs-on: self-hosted

    needs:
      - build

    steps:
      - name: remove old container
        run: |
          docker rm --force todo-flask-app

      - name: run new container
        run: |
          docker run -d --restart unless-stopped --name todo-flask-app -p 2000:3000 todo-flask-app:${{ github.sha }}
